typography_spectrum: 0.859561680816114
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7708371647167951
  lightness: 0.584225608734414
  saturation: 0.5437700506299734
  rhythmicContrast: 0.32971085561439395
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23520523542538285
analytics:
  google: null
  facebook: null
  twitter: null
name: ExperienceInspiration
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: noitaripsnI detcepxenU
purpose: []
